Better error messages

diff --git a/.bin/tmux-manager b/.bin/tmux-manager
--- a/.bin/tmux-manager
+++ b/.bin/tmux-manager
@@ -2,6 +2,34 @@
 
 set -eou pipefail
 
+if [[ -t 2 && -z "${NO_COLOR:-}" ]]; then
+  if command -v tput &>/dev/null && \
+	  tput colors &>/dev/null; then
+    RED="$(tput setaf 1)"
+    BOLD="$(tput bold)"
+    RESET="$(tput sgr0)"
+  fi
+fi
+
+error() {
+  local msg="$1"
+  local code="${2:-1}"
+
+  local error_string="ERROR"
+
+  if [[ -n "${RED:-}" ]]; then
+    printf '%s%s%s:%s %s\n' "$BOLD" "$RED" "$error_string" "$RESET" "$msg" >&2
+  else
+    printf '%s: %s\n' "$error_string" "$msg" >&2
+  fi
+
+  exit "$code"
+}
+
+if ! command -v tmux &>/dev/null; then
+	error "Tmux executable not found" 3
+fi
+
 # Global variables
 SEARCH_FOLDERS="$HOME/code"
 
@@ -65,8 +93,7 @@ validate_session_path()
 		return 0
 	fi
 
-	echo "The directory \"$session_path\" or session \"$session_name\" does not exist" >&2
-	return 1
+	error "The directory \"$session_path\" or session \"$session_name\" does not exist"
 }
 
 get_session_fzf()
@@ -148,8 +175,7 @@ elif [[ $# -eq 1 ]]; then
 	fi
 else
 	show_help
-	echo "ERROR: More than 2 arguments" >&2
-	exit 1
+	error "More than 2 arguments"
 fi
 
 SESSION_NAME="$(get_session_name "$SESSION_PATH")"
